services:
  trackncore:
    image: ghcr.io/skidoodle/trackncore:main
    container_name: trackncore
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - data:/app

volumes:
  data:
